cluster.name: yoka_master

node.name: "yoka.node2"
node.master: true
node.data: true
index.number_of_shards: 5
index.number_of_replicas: 1
network.host: 10.46.214.164

http.port: 9200
transport.tcp.compress: true
transport.tcp.port: 9300

discovery.zen.ping.unicast.hosts: ["10.46.214.130"]
discovery.zen.fd.connect_on_network_disconnect : true  
discovery.zen.initial_ping_timeout : 10s  
discovery.zen.fd.ping_interval : 2s  
discovery.zen.fd.ping_retries  : 10 